(function(){
  "use strict";
  const $=id=>document.getElementById(id);
  const REGIONS={1:"Kanto",2:"Johto",3:"Hoenn",4:"Sinnoh",5:"Unova",6:"Kalos",7:"Alola",8:"Galar",9:"Paldea"};
  const sprite=(id,shiny=true)=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${shiny?"shiny/":""}${id}.png`;
  let authMode="create",hallMode="region",dex=[],pokemon=[];
  const message=(text,error=false)=>{const el=$(error?"accountError":"accountMessage");el.textContent=text;el.hidden=!text;if(text)$(error?"accountMessage":"accountError").hidden=true;};
  const teamHtml=team=>`<div class="team">${team.map(m=>`<span class="mon ${m.mega?"mega":""} ${m.shiny?"shiny":""}"><img src="${sprite(m.id,m.shiny)}" alt="${m.name}" onerror="this.onerror=null;this.src='${sprite(m.base_id||m.id,m.shiny)}'">${m.mega?'<span class="mega-mark">&#9672;</span>':""}${m.shiny?'<span class="shiny-mark">&#10022;</span>':""}</span>`).join("")}</div>`;
  function regionOptions(){return '<option value="">All regions</option>'+Object.entries(REGIONS).map(([n,v])=>`<option value="${n}">${v}</option>`).join("");}
  function setAuthMode(mode){authMode=mode;[...$("authTabs").children].forEach(b=>b.classList.toggle("on",b.dataset.auth===mode));$("usernameWrap").hidden=mode!=="create";$("authUsername").required=mode==="create";$("authPassword").autocomplete=mode==="create"?"new-password":"current-password";$("authTitle").textContent=mode==="create"?"Create your account":"Welcome back";$("authCopy").textContent=mode==="create"?"Your runs already saved on this device will stay with you.":"Sign in to bring your account and collection onto this device.";$("authSubmit").textContent=mode==="create"?"Create Account":"Sign In";}
  async function refreshAccount(){const a=await DexleStats.account();$("signedOut").hidden=!a.anonymous;$("signedIn").hidden=a.anonymous;if(!a.anonymous){$("profileName").textContent=a.profile?.username||a.user.user_metadata?.username||"Trainer";$("profileEmail").textContent=a.user.email||"";}return a;}
  async function refreshHall(){$("hallFilters").hidden=hallMode==="gauntlet";$("hallList").innerHTML='<p class="empty">Loading flawless runs…</p>';try{const rows=await DexleStats.hallOfFame(hallMode,hallMode==="region"?(+$("hallRegion").value||null):null);$("hallList").innerHTML=rows.length?rows.map(r=>`<article class="hall-card"><div class="hall-head"><span class="hall-user">@${r.username}</span><b>${r.mode==="gauntlet"?"Nine-region Gauntlet":REGIONS[r.region]}</b><span class="hall-date">${new Date(r.created_at).toLocaleDateString()}</span><span class="record"><span class="wins">${r.wins}</span><i>–</i><span class="losses">${r.losses}</span></span></div>${teamHtml(r.team)}</article>`).join(""):'<p class="empty">No flawless run has claimed this Hall of Fame yet.</p>';}catch(e){message(e.message,true);}}
  function drawDex(){const collected=new Map(dex.map(x=>[x.form_key,x]));let cards=pokemon.map(p=>{const hit=collected.get(`base:${p.id}`);return{base:p.id,recent:hit?.last_seen_at||"",html:`<div class="dex-mon ${hit?"":"locked"}" title="${p.name}">${hit?`<img loading="lazy" src="${sprite(p.id)}" alt="${p.name}">`:""}<b>${p.name}</b><small>#${String(p.id).padStart(4,"0")}</small>${hit&&Date.now()-new Date(hit.last_seen_at)<604800000?'<span class="dex-new">New</span>':""}</div>`};});dex.filter(x=>x.is_mega||x.pokemon_id!==x.base_id).forEach(x=>cards.push({base:x.base_id,recent:x.last_seen_at,html:`<div class="dex-mon ${x.is_mega?"mega":""}">${x.is_mega?'<span class="dex-gem">&#9672;</span>':""}<img loading="lazy" src="${sprite(x.pokemon_id)}" alt="${x.pokemon_name}" onerror="this.onerror=null;this.src='${sprite(x.base_id)}'"><b>${x.pokemon_name}</b><small>${x.is_mega?"Mega":"Alternate"} form</small></div>`}));if($("shinySort").value==="recent")cards.sort((a,b)=>String(b.recent).localeCompare(String(a.recent))||a.base-b.base);else cards.sort((a,b)=>a.base-b.base);$("shinyGrid").innerHTML=cards.map(x=>x.html).join("");const bases=new Set(dex.filter(x=>!x.is_mega&&x.pokemon_id===x.base_id).map(x=>x.base_id)).size,forms=dex.filter(x=>x.is_mega||x.pokemon_id!==x.base_id).length;$("shinyCount").textContent=`${bases} / 1025`;$("formCount").textContent=`${forms} bonus form${forms===1?"":"s"}`;$("shinyBar").style.width=`${bases/1025*100}%`;}
  async function refreshDex(){try{dex=await DexleStats.shinyDex();drawDex();}catch(e){message(e.message,true);}}
  async function init(){if(!DexleStats.configured)return message("Connect Supabase before using accounts.",true);$("hallRegion").innerHTML=regionOptions();try{pokemon=await fetch("pokedex.json").then(r=>r.json());await refreshAccount();await Promise.all([refreshHall(),refreshDex()]);}catch(e){message(e.message,true);}}
  $("authTabs").onclick=e=>{const b=e.target.closest("[data-auth]");if(b)setAuthMode(b.dataset.auth);};
  $("authForm").onsubmit=async e=>{e.preventDefault();$("authSubmit").disabled=true;try{if(authMode==="create"){await DexleStats.createAccount($("authEmail").value,$("authPassword").value,$("authUsername").value);message("Account created. Check your email if confirmation is enabled.");}else{await DexleStats.signIn($("authEmail").value,$("authPassword").value);message("Signed in successfully.");}await refreshAccount();await refreshDex();}catch(err){message(err.message,true);}finally{$("authSubmit").disabled=false;}};
  $("signOut").onclick=async()=>{await DexleStats.signOut();location.reload();};
  $("hallTabs").onclick=e=>{const b=e.target.closest("[data-mode]");if(!b)return;hallMode=b.dataset.mode;[...$("hallTabs").children].forEach(x=>x.classList.toggle("on",x===b));refreshHall();};
  $("hallRegion").onchange=refreshHall;$("shinySort").onchange=drawDex;setAuthMode("create");init();
})();
