(()=>{"use strict";
const $=id=>document.getElementById(id),ROOT="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/";
let state=null,selected=new Set(),previousSolved=0,previousMistakes=0;
const sprite=p=>ROOT+(p.sprite||`${p.id}.png`);
const solvedIds=()=>new Set((state?.solved||[]).flatMap(g=>g.pokemon.map(p=>+p.id)));
function draw(){if(!state)return;const solved=solvedIds(),remaining=state.cards.filter(p=>!solved.has(+p.id));$("solvedGroups").innerHTML=(state.solved||[]).map(g=>`<article class="solved-row ${g.tier}"><h3>${g.label}</h3><div class="solved-pokemon">${g.pokemon.map(p=>`<span>${p.name}</span>`).join("")}</div></article>`).join("");$("connectionGrid").innerHTML=remaining.map(p=>`<button class="connection-card ${selected.has(+p.id)?"selected":""}" data-id="${p.id}" ${state.completed?"disabled":""}><img src="${sprite(p)}" alt=""><b>${p.name}</b></button>`).join("");$("connectionGrid").querySelectorAll("[data-id]").forEach(card=>card.onclick=()=>toggle(+card.dataset.id));const left=Math.max(0,4-state.mistakes);$("mistakeDots").innerHTML=Array.from({length:4},(_,i)=>`<i class="${i>=left?"used":""}"></i>`).join("");$("mistakeDots").setAttribute("aria-label",`${left} mistake${left===1?"":"s"} remaining`);$("submitConnection").disabled=state.completed||selected.size!==4;$("deselectAll").disabled=state.completed||!selected.size;$("connectionResult").hidden=!state.completed;if(state.completed){$("connectionResultTitle").textContent=state.won?"All connections found!":"Better luck tomorrow";$("connectionResultCopy").textContent=state.won?`You solved today’s puzzle with ${state.mistakes} mistake${state.mistakes===1?"":"s"}.`:"The remaining connections have been revealed.";} }
function toggle(id){if(state.completed)return;if(selected.has(id))selected.delete(id);else if(selected.size<4)selected.add(id);draw()}
function message(text,bad=false){const el=$("connectionStatus");el.textContent=text;el.classList.toggle("bad",bad);if(bad){el.style.animation="none";void el.offsetWidth;el.style.animation=""}}
async function submit(){if(selected.size!==4)return;const button=$("submitConnection");button.disabled=true;previousSolved=state.solved.length;previousMistakes=state.mistakes;try{state=await DexleStats.submitPokeConnections([...selected]);selected.clear();if(state.completed&&!state.won)message("No mistakes left.",true);else if(state.solved.length>previousSolved)message(state.completed?"Masterful! Puzzle complete.":"Connection found!");else if(state.mistakes>previousMistakes)message("Not a connection—try again.",true);draw()}catch(error){message(error.message,true);button.disabled=false}}
async function share(){const count=state.solved_count??state.solved.length,marks=["🔴","🔵","🟡","🟣"].slice(0,count).join(""),text=`PokéConnections ${state.date}\n${marks}\n${state.won?`Solved with ${state.mistakes}/4 mistakes`:`${count}/4 connections`}\ndexle.io`;try{if(navigator.share)await navigator.share({title:"My PokéConnections result",text});else await navigator.clipboard.writeText(text);$("shareConnectionsStatus").textContent="Result copied!"}catch(error){if(error.name!=="AbortError")$("shareConnectionsStatus").textContent="Could not share result."}}
async function load(){if(!window.DexleStats?.configured){$("connectionNotice").hidden=false;$("connectionNotice").textContent="PokéConnections is not connected to Supabase yet.";return}try{state=await DexleStats.pokeConnectionsToday();$("connectionNotice").hidden=true;draw()}catch(error){$("connectionNotice").hidden=false;$("connectionNotice").textContent=/function.*does not exist|schema cache/i.test(error.message)?"PokéConnections needs its database setup. Run supabase-poke-connections.sql in Supabase.":error.message;$("connectionGrid").innerHTML=""}}
$("submitConnection").onclick=submit;$("deselectAll").onclick=()=>{selected.clear();message("");draw()};$("shareConnections").onclick=share;load();
})();
