(()=>{"use strict";
const $=id=>document.getElementById(id),REGIONS={1:"Kanto",2:"Johto",3:"Hoenn",4:"Sinnoh",5:"Unova",6:"Kalos",7:"Alola",8:"Galar",9:"Paldea"};
const root="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/",sprite=(id,shiny=true)=>`${root}${shiny?"shiny/":""}${id}.png`,candy="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rare-candy.png";
let pokemon=[],profile=null,hallMode="region",visible=27;
const msg=(text,error=false)=>{const el=$("friendMessage");el.textContent=text;el.classList.toggle("error",error);el.hidden=!text;};
const monSprite=m=>{if(+m.id===10301)return"assets/megas/mega-zygarde.png";const custom=m.shiny?m.shiny_sprite:m.sprite;return custom?root+custom:sprite(m.id,m.shiny);};
const teamHtml=team=>`<div class="team">${team.map(m=>`<span class="mon ${m.mega?"mega":""} ${m.type_form?"type-form":""} ${m.shiny?"shiny":""} ${m.candy?"candy":""}"><img src="${monSprite(m)}" alt="${m.name}" onerror="this.onerror=null;this.src='${sprite(m.base_id||m.id,m.shiny)}'">${m.candy?`<span class="candy-mark"><img src="${candy}" alt="Rare Candy"></span>`:""}${m.mega?'<span class="mega-mark">&#9672;</span>':""}${m.type_form?'<span class="type-form-mark">&#9671;</span>':""}${m.shiny?'<span class="shiny-mark">&#10022;</span>':""}</span>`).join("")}</div>`;
const hallCard=r=>`<article class="hall-card flawless"><div class="hall-head"><span class="rankball oak-disc"></span><b>${r.mode==="gauntlet"?"Gauntlet":REGIONS[r.region]}</b><span class="hall-date">${new Date(r.created_at).toLocaleDateString()}</span><div class="team-metrics"><span>Stats <b>${Number(r.team_bst||0).toLocaleString()}</b></span><span>Coverage <b>${r.coverage??0}/18</b></span></div><span class="record"><span class="wins">${r.wins}</span><i>–</i><span class="losses">${r.losses}</span></span></div>${teamHtml(r.team||[])}</article>`;
const friendRow=(x,kind)=>`<div class="friend-row"><b>${x.username}</b>${kind==="incoming"?`<button class="accept" data-accept="${x.id}">Accept</button><button class="remove" data-remove="${x.id}">Decline</button>`:kind==="outgoing"?`<small>Request sent</small><button class="remove" data-remove="${x.id}">Cancel</button>`:`<button class="view-friend" data-view="${x.other_id}">View profile</button><button class="remove" data-remove="${x.id}">Remove</button>`}</div>`;
async function refresh(){const rows=await DexleStats.friendConnections(),pending=rows.filter(x=>x.status==="pending"),friends=rows.filter(x=>x.status==="accepted");$("friendRequests").innerHTML=pending.length?pending.map(x=>friendRow(x,x.incoming?"incoming":"outgoing")).join(""):'<p class="empty">No pending requests.</p>';$("friendList").innerHTML=friends.length?friends.map(x=>friendRow(x,"friend")).join(""):'<p class="empty">No friends yet.</p>';}
function drawHall(){const rows=(profile.hall||[]).filter(r=>r.mode===hallMode),region=hallMode==="region";$("friendBadges").hidden=!region;$("friendHallDetail").hidden=region;if(!region){$("friendHallDetail").hidden=false;$("friendBadgeBack").hidden=true;$("friendBadgeTitle").textContent="Flawless Gauntlet teams";$("friendHallTeams").innerHTML=rows.length?rows.map(hallCard).join(""):'<p class="empty">No flawless Gauntlet teams yet.</p>';return;}$("friendBadges").innerHTML=Object.entries(REGIONS).map(([id,name])=>{const earned=rows.some(r=>+r.region===+id);return `<button class="region-badge ${earned?"earned":"locked"}" data-region="${id}" ${earned?"":"disabled"}><span class="badge-disc"><i>${earned?"&#9733;":""}</i></span><b>${name}</b>${earned?"<small>Champion</small>":""}</button>`}).join("");$("friendBadges").querySelectorAll(".earned").forEach(b=>b.onclick=()=>{$("friendBadges").hidden=true;$("friendHallDetail").hidden=false;$("friendBadgeBack").hidden=false;$("friendBadgeTitle").textContent=`${REGIONS[b.dataset.region]} flawless teams`;$("friendHallTeams").innerHTML=rows.filter(r=>+r.region===+b.dataset.region).map(hallCard).join("");});}
function drawDex(){const dex=profile.shinies||[],hits=new Map(dex.map(x=>[x.form_key,x]));let cards=pokemon.map(p=>{const h=hits.get(`base:${p.id}`);return{base:p.id,recent:h?.last_seen_at||"",html:`<${h?'a href="dexle.html?pokemon='+p.id+'&shiny=1"':'div'} class="dex-mon ${h?"":"locked"}">${h?`<img loading="lazy" src="${sprite(p.id)}" alt="${p.name}">`:""}<b>${p.name}</b><small>#${String(p.id).padStart(4,"0")}</small></${h?'a':'div'}>`}});dex.filter(x=>x.is_mega||x.pokemon_id!==x.base_id).forEach(x=>cards.push({base:x.base_id,recent:x.last_seen_at,html:`<div class="dex-mon ${x.is_mega?"mega":""}">${x.is_mega?'<span class="dex-gem">&#9672;</span>':""}<img loading="lazy" src="${+x.pokemon_id===10301?'assets/megas/mega-zygarde.png':sprite(x.pokemon_id)}" onerror="this.onerror=null;this.src='${sprite(x.base_id)}'"><b>${x.pokemon_name}</b><small>${x.is_mega?"Mega":"Alternate"} form</small></div>`}));cards.sort($("friendShinySort").value==="recent"?(a,b)=>String(b.recent).localeCompare(String(a.recent))||a.base-b.base:(a,b)=>a.base-b.base);$("friendShinyGrid").innerHTML=cards.slice(0,visible).map(x=>x.html).join("");$("friendShinyMore").hidden=visible>=cards.length;const bases=new Set(dex.filter(x=>!x.is_mega&&x.pokemon_id===x.base_id).map(x=>x.base_id)).size,forms=dex.filter(x=>x.is_mega||x.pokemon_id!==x.base_id).length;$("friendShinyCount").textContent=`${bases} / 1025`;$("friendFormCount").textContent=`${forms} bonus form${forms===1?"":"s"}`;$("friendShinyBar").style.width=`${bases/1025*100}%`;}
async function view(id){profile=await DexleStats.friendProfile(id);visible=27;hallMode="region";$("friendHallTitle").textContent=`${profile.username}'s Hall of Fame`;$("friendDexTitle").textContent=`${profile.username}'s Shiny Dex`;$("friendHome").hidden=true;$("friendProfile").hidden=false;[...$("friendHallTabs").children].forEach(x=>x.classList.toggle("on",x.dataset.mode==="region"));drawHall();drawDex();scrollTo({top:0,behavior:"smooth"});}
$("friendSearch").onsubmit=async e=>{e.preventDefault();const rows=await DexleStats.searchTrainers($("friendQuery").value);$("friendResults").innerHTML=rows.length?rows.map(x=>`<div class="friend-row"><b>${x.username}</b><button class="accept" data-add="${x.user_id}">Send request</button></div>`).join(""):'<p class="empty">No Trainers found.</p>';};
$("friendHome").onclick=async e=>{const b=e.target.closest("button[data-add],button[data-accept],button[data-remove],button[data-view]");if(!b)return;b.disabled=true;try{if(b.dataset.add)await DexleStats.sendFriendRequest(b.dataset.add);else if(b.dataset.accept)await DexleStats.acceptFriendRequest(b.dataset.accept);else if(b.dataset.remove)await DexleStats.removeFriendConnection(b.dataset.remove);else return await view(b.dataset.view);$("friendResults").innerHTML="";await refresh();}catch(err){msg(err.message,true)}finally{b.disabled=false}};
$("friendBack").onclick=()=>{$("friendProfile").hidden=true;$("friendHome").hidden=false;profile=null};$("friendHallTabs").onclick=e=>{const b=e.target.closest("[data-mode]");if(!b)return;hallMode=b.dataset.mode;[...$("friendHallTabs").children].forEach(x=>x.classList.toggle("on",x===b));drawHall()};$("friendShinySort").onchange=()=>{visible=27;drawDex()};$("friendShinyMore").onclick=()=>{visible+=27;drawDex()};
$("friendBadgeBack").onclick=()=>{$("friendHallDetail").hidden=true;$("friendBadges").hidden=false};
(async()=>{try{pokemon=await fetch("pokedex.json").then(r=>r.json());const a=await DexleStats.account();if(a.anonymous){$("accountNeeded").hidden=false;return}$("friendHome").hidden=false;await refresh()}catch(e){msg(e.message,true)}})();
})();
