-- PokéConnections daily puzzle bank and server-authoritative player progress.
create table if not exists public.poke_connections_puzzles (
  id bigint generated by default as identity primary key,
  title text not null,
  groups jsonb not null check (jsonb_typeof(groups)='array' and jsonb_array_length(groups)=4),
  card_order integer[] not null,
  created_at timestamptz not null default now()
);

create table if not exists public.poke_connections_results (
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_date date not null,
  puzzle_id bigint not null references public.poke_connections_puzzles(id),
  solved_tiers text[] not null default '{}',
  mistakes smallint not null default 0 check (mistakes between 0 and 4),
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id,challenge_date)
);

alter table public.poke_connections_puzzles enable row level security;
alter table public.poke_connections_results enable row level security;
revoke all on public.poke_connections_puzzles from anon,authenticated;
revoke all on public.poke_connections_results from anon,authenticated;

insert into public.poke_connections_puzzles (id,title,groups,card_order) values
(1,'Partners and Champions','[
 {"tier":"poke","label":"Eevee evolutions","pokemon":[{"id":134,"name":"Vaporeon"},{"id":135,"name":"Jolteon"},{"id":136,"name":"Flareon"},{"id":700,"name":"Sylveon"}]},
 {"tier":"great","label":"Pokémon caught by Ash","pokemon":[{"id":25,"name":"Pikachu"},{"id":6,"name":"Charizard"},{"id":254,"name":"Sceptile"},{"id":658,"name":"Greninja"}]},
 {"tier":"ultra","label":"Members of Cynthia’s team","pokemon":[{"id":445,"name":"Garchomp"},{"id":442,"name":"Spiritomb"},{"id":407,"name":"Roserade"},{"id":350,"name":"Milotic"}]},
 {"tier":"master","label":"Names ending in “don”","pokemon":[{"id":383,"name":"Groudon"},{"id":1007,"name":"Koraidon"},{"id":1008,"name":"Miraidon"},{"id":112,"name":"Rhydon"}]}
]'::jsonb,array[25,134,445,383,700,254,112,350,135,407,1007,6,136,658,442,1008]),
(2,'Evolution Methods','[
 {"tier":"poke","label":"Kanto starter choices","pokemon":[{"id":1,"name":"Bulbasaur"},{"id":4,"name":"Charmander"},{"id":7,"name":"Squirtle"},{"id":25,"name":"Pikachu"}]},
 {"tier":"great","label":"Evolve by trading","pokemon":[{"id":65,"name":"Alakazam"},{"id":68,"name":"Machamp"},{"id":94,"name":"Gengar"},{"id":76,"name":"Golem"}]},
 {"tier":"ultra","label":"Later evolutions introduced in Sinnoh","pokemon":[{"id":466,"name":"Electivire"},{"id":467,"name":"Magmortar"},{"id":464,"name":"Rhyperior"},{"id":461,"name":"Weavile"}]},
 {"tier":"master","label":"Rotom appliance forms","pokemon":[{"id":10008,"name":"Heat Rotom","sprite":"10008.png"},{"id":10009,"name":"Wash Rotom","sprite":"10009.png"},{"id":10010,"name":"Frost Rotom","sprite":"10010.png"},{"id":10012,"name":"Mow Rotom","sprite":"10012.png"}]}
]'::jsonb,array[65,1,10009,466,25,94,461,10008,4,467,76,10012,7,68,464,10010]),
(3,'Giants and Babies','[
 {"tier":"poke","label":"Legendary giants","pokemon":[{"id":377,"name":"Regirock"},{"id":378,"name":"Regice"},{"id":379,"name":"Registeel"},{"id":486,"name":"Regigigas"}]},
 {"tier":"great","label":"Baby Pokémon introduced in Johto","pokemon":[{"id":172,"name":"Pichu"},{"id":173,"name":"Cleffa"},{"id":174,"name":"Igglybuff"},{"id":175,"name":"Togepi"}]},
 {"tier":"ultra","label":"Team Rocket’s anime partners","pokemon":[{"id":52,"name":"Meowth"},{"id":24,"name":"Arbok"},{"id":110,"name":"Weezing"},{"id":202,"name":"Wobbuffet"}]},
 {"tier":"master","label":"Cross-generation evolutions added in Sinnoh","pokemon":[{"id":466,"name":"Electivire"},{"id":467,"name":"Magmortar"},{"id":464,"name":"Rhyperior"},{"id":461,"name":"Weavile"}]}
]'::jsonb,array[172,377,52,466,378,202,461,173,24,467,379,175,464,110,486,174]),
(4,'Alola and Hisui','[
 {"tier":"poke","label":"Alola’s island guardians","pokemon":[{"id":785,"name":"Tapu Koko"},{"id":786,"name":"Tapu Lele"},{"id":787,"name":"Tapu Bulu"},{"id":788,"name":"Tapu Fini"}]},
 {"tier":"great","label":"Ultra Beasts","pokemon":[{"id":793,"name":"Nihilego"},{"id":794,"name":"Buzzwole"},{"id":795,"name":"Pheromosa"},{"id":796,"name":"Xurkitree"}]},
 {"tier":"ultra","label":"Ancient Paradox Pokémon","pokemon":[{"id":984,"name":"Great Tusk"},{"id":985,"name":"Scream Tail"},{"id":986,"name":"Brute Bonnet"},{"id":987,"name":"Flutter Mane"}]},
 {"tier":"master","label":"New evolutions discovered in Hisui","pokemon":[{"id":899,"name":"Wyrdeer"},{"id":900,"name":"Kleavor"},{"id":901,"name":"Ursaluna"},{"id":902,"name":"Basculegion"}]}
]'::jsonb,array[793,985,785,899,794,901,787,987,900,795,984,786,902,788,986,796]),
(5,'Paldea Patterns','[
 {"tier":"poke","label":"Treasures of Ruin","pokemon":[{"id":1001,"name":"Wo-Chien"},{"id":1002,"name":"Chien-Pao"},{"id":1003,"name":"Ting-Lu"},{"id":1004,"name":"Chi-Yu"}]},
 {"tier":"great","label":"The Loyal Three and their leader","pokemon":[{"id":1014,"name":"Okidogi"},{"id":1015,"name":"Munkidori"},{"id":1016,"name":"Fezandipiti"},{"id":1025,"name":"Pecharunt"}]},
 {"tier":"ultra","label":"Future Paradox Pokémon","pokemon":[{"id":990,"name":"Iron Treads"},{"id":991,"name":"Iron Bundle"},{"id":992,"name":"Iron Hands"},{"id":993,"name":"Iron Jugulis"}]},
 {"tier":"master","label":"Paldean convergent species","pokemon":[{"id":948,"name":"Toedscool"},{"id":949,"name":"Toedscruel"},{"id":960,"name":"Wiglett"},{"id":961,"name":"Wugtrio"}]}
]'::jsonb,array[1001,991,948,1014,1003,992,960,1016,949,1002,993,1025,961,990,1015,1004]),
(6,'Legends and Wordplay','[
 {"tier":"poke","label":"Swords of Justice","pokemon":[{"id":638,"name":"Cobalion"},{"id":639,"name":"Terrakion"},{"id":640,"name":"Virizion"},{"id":647,"name":"Keldeo"}]},
 {"tier":"great","label":"Forces of Nature","pokemon":[{"id":641,"name":"Tornadus"},{"id":642,"name":"Thundurus"},{"id":645,"name":"Landorus"},{"id":905,"name":"Enamorus"}]},
 {"tier":"ultra","label":"Galar’s restored fossil Pokémon","pokemon":[{"id":880,"name":"Dracozolt"},{"id":881,"name":"Arctozolt"},{"id":882,"name":"Dracovish"},{"id":883,"name":"Arctovish"}]},
 {"tier":"master","label":"Names start and end with the same letter","pokemon":[{"id":63,"name":"Abra"},{"id":133,"name":"Eevee"},{"id":203,"name":"Girafarig"},{"id":250,"name":"Ho-Oh"}]}
]'::jsonb,array[641,880,638,133,642,63,882,640,203,905,881,639,250,883,647,645])
on conflict (id) do update set title=excluded.title,groups=excluded.groups,card_order=excluded.card_order;

-- Build 50 additional daily boards from the curated tier banks above. Each
-- board has one group per difficulty and is rejected if a Pokemon would occur
-- twice. IDs 7-56 are stable, so this block is safe to run again after edits.
do $$
declare
  v_poke jsonb[]; v_great jsonb[]; v_ultra jsonb[]; v_master jsonb[];
  v_groups jsonb; v_order integer[]; v_code integer; v_try integer:=0;
  v_a integer; v_b integer; v_c integer; v_d integer;
  v_total integer; v_unique integer; v_made integer:=0;
begin
  select array_agg(grp order by p.id) filter(where grp->>'tier'='poke'),
         array_agg(grp order by p.id) filter(where grp->>'tier'='great'),
         array_agg(grp order by p.id) filter(where grp->>'tier'='ultra'),
         array_agg(grp order by p.id) filter(where grp->>'tier'='master')
    into v_poke,v_great,v_ultra,v_master
    from public.poke_connections_puzzles p
    cross join lateral jsonb_array_elements(p.groups) grp
    where p.id between 1 and 6;
  while v_made<50 and v_try<1296 loop
    v_code:=mod(v_try*37,1296); v_try:=v_try+1;
    v_a:=mod(v_code,6)+1; v_b:=mod(v_code/6,6)+1;
    v_c:=mod(v_code/36,6)+1; v_d:=mod(v_code/216,6)+1;
    if v_a=v_b and v_b=v_c and v_c=v_d then continue; end if;
    v_groups:=jsonb_build_array(v_poke[v_a],v_great[v_b],v_ultra[v_c],v_master[v_d]);
    select count(*),count(distinct (mon->>'id')::integer) into v_total,v_unique
      from jsonb_array_elements(v_groups) grp
      cross join lateral jsonb_array_elements(grp->'pokemon') mon;
    if v_total<>16 or v_unique<>16 then continue; end if;
    v_made:=v_made+1;
    select array_agg((mon->>'id')::integer order by
      md5((mon->>'id') || ':' || (6+v_made)::text)) into v_order
      from jsonb_array_elements(v_groups) grp
      cross join lateral jsonb_array_elements(grp->'pokemon') mon;
    insert into public.poke_connections_puzzles(id,title,groups,card_order)
      values(6+v_made,'Daily Mix '||lpad(v_made::text,2,'0'),v_groups,v_order)
      on conflict(id) do update set title=excluded.title,groups=excluded.groups,
        card_order=excluded.card_order;
  end loop;
  if v_made<>50 then raise exception 'Could only build % valid daily boards',v_made; end if;
end $$;

select setval(pg_get_serial_sequence('public.poke_connections_puzzles','id'),
  (select max(id) from public.poke_connections_puzzles));

create or replace function public.poke_connections_today()
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_user uuid:=auth.uid(); v_date date:=(now() at time zone 'America/Denver')::date;
  v_count integer; v_puzzle public.poke_connections_puzzles%rowtype;
  v_result public.poke_connections_results%rowtype; v_cards jsonb; v_groups jsonb;
begin
  if v_user is null then raise exception 'Sign-in required'; end if;
  select count(*) into v_count from public.poke_connections_puzzles;
  if v_count=0 then raise exception 'No PokéConnections puzzles are installed'; end if;
  select * into v_puzzle from public.poke_connections_puzzles
    order by id offset mod(v_date-date '2026-01-01',v_count) limit 1;
  insert into public.poke_connections_results(user_id,challenge_date,puzzle_id)
    values(v_user,v_date,v_puzzle.id) on conflict do nothing;
  select * into v_result from public.poke_connections_results
    where user_id=v_user and challenge_date=v_date;
  select jsonb_agg(card order by array_position(v_puzzle.card_order,(card->>'id')::integer)) into v_cards
    from jsonb_array_elements(v_puzzle.groups) grp
    cross join lateral jsonb_array_elements(grp->'pokemon') card;
  if v_result.mistakes>=4 then v_groups:=v_puzzle.groups;
  else
    select coalesce(jsonb_agg(grp order by array_position(v_result.solved_tiers,grp->>'tier')),'[]'::jsonb)
      into v_groups from jsonb_array_elements(v_puzzle.groups) grp
      where grp->>'tier'=any(v_result.solved_tiers);
  end if;
  return jsonb_build_object('date',v_date,'title',v_puzzle.title,'cards',v_cards,
    'solved',v_groups,'mistakes',v_result.mistakes,'completed',v_result.completed,
    'won',cardinality(v_result.solved_tiers)=4,'solved_count',cardinality(v_result.solved_tiers));
end; $$;

create or replace function public.submit_poke_connections(p_ids integer[])
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_user uuid:=auth.uid(); v_date date:=(now() at time zone 'America/Denver')::date;
  v_result public.poke_connections_results%rowtype; v_puzzle public.poke_connections_puzzles%rowtype;
  v_match jsonb; v_ids integer[];
begin
  if v_user is null then raise exception 'Sign-in required'; end if;
  select array_agg(x order by x) into v_ids from (select distinct unnest(p_ids) x) q;
  if cardinality(v_ids)<>4 then raise exception 'Select exactly four different Pokémon'; end if;
  select * into v_result from public.poke_connections_results
    where user_id=v_user and challenge_date=v_date for update;
  if not found then perform public.poke_connections_today(); select * into v_result
    from public.poke_connections_results where user_id=v_user and challenge_date=v_date for update; end if;
  if v_result.completed then return public.poke_connections_today(); end if;
  select * into v_puzzle from public.poke_connections_puzzles where id=v_result.puzzle_id;
  select grp into v_match from jsonb_array_elements(v_puzzle.groups) grp
    where not (grp->>'tier'=any(v_result.solved_tiers)) and
      (select array_agg((mon->>'id')::integer order by (mon->>'id')::integer)
       from jsonb_array_elements(grp->'pokemon') mon)=v_ids limit 1;
  if v_match is not null then
    update public.poke_connections_results set
      solved_tiers=array_append(solved_tiers,v_match->>'tier'),
      completed=(cardinality(solved_tiers)+1=4),updated_at=now()
      where user_id=v_user and challenge_date=v_date;
  else
    update public.poke_connections_results set mistakes=least(4,mistakes+1),
      completed=(mistakes+1>=4),updated_at=now()
      where user_id=v_user and challenge_date=v_date;
  end if;
  return public.poke_connections_today();
end; $$;

revoke execute on function public.poke_connections_today() from public,anon;
revoke execute on function public.submit_poke_connections(integer[]) from public,anon;
grant execute on function public.poke_connections_today() to authenticated;
grant execute on function public.submit_poke_connections(integer[]) to authenticated;
