(()=>{"use strict";
const $=id=>document.getElementById(id),ROOT="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/";
const TYPES=["normal","fire","water","electric","grass","ice","fighting","poison","ground","flying","psychic","bug","rock","ghost","dragon","dark","steel","fairy"];
const COLORS={normal:"#9FA19F",fire:"#E62829",water:"#2980EF",electric:"#C9A000",grass:"#3FA129",ice:"#3D9FB3",fighting:"#D56718",poison:"#9141CB",ground:"#915121",flying:"#6199C9",psychic:"#CF3769",bug:"#71810F",rock:"#8F8961",ghost:"#704170",dragon:"#5060E1",dark:"#50413F",steel:"#508198",fairy:"#CF50CF"};
const CHART={normal:{rock:.5,ghost:0,steel:.5},fire:{fire:.5,water:.5,grass:2,ice:2,bug:2,rock:.5,dragon:.5,steel:2},water:{fire:2,water:.5,grass:.5,ground:2,rock:2,dragon:.5},electric:{water:2,electric:.5,grass:.5,ground:0,flying:2,dragon:.5},grass:{fire:.5,water:2,grass:.5,poison:.5,ground:2,flying:.5,bug:.5,rock:2,dragon:.5,steel:.5},ice:{fire:.5,water:.5,grass:2,ice:.5,ground:2,flying:2,dragon:2,steel:.5},fighting:{normal:2,ice:2,poison:.5,flying:.5,psychic:.5,bug:.5,rock:2,ghost:0,dark:2,steel:2,fairy:.5},poison:{grass:2,poison:.5,ground:.5,rock:.5,ghost:.5,steel:0,fairy:2},ground:{fire:2,electric:2,grass:.5,poison:2,flying:0,bug:.5,rock:2,steel:2},flying:{electric:.5,grass:2,fighting:2,bug:2,rock:.5,steel:.5},psychic:{fighting:2,poison:2,psychic:.5,dark:0,steel:.5},bug:{fire:.5,grass:2,fighting:.5,poison:.5,flying:.5,psychic:2,ghost:.5,dark:2,steel:.5,fairy:.5},rock:{fire:2,ice:2,fighting:.5,ground:.5,flying:2,bug:2,steel:.5},ghost:{normal:0,psychic:2,ghost:2,dark:.5},dragon:{dragon:2,steel:.5,fairy:0},dark:{fighting:.5,psychic:2,ghost:2,dark:.5,fairy:.5},steel:{fire:.5,water:.5,electric:.5,ice:2,rock:2,steel:.5,fairy:2},fairy:{fire:.5,fighting:2,poison:.5,dragon:2,dark:2,steel:.5}};
let dex=[],forms={},megas={},entries=[],team=[],shiny=false;
const norm=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]/g,"");
const sprite=p=>+p.id===10301?"assets/megas/mega-zygarde.png":p[shiny?"shinySprite":"sprite"]?ROOT+p[shiny?"shinySprite":"sprite"]:ROOT+(shiny?"shiny/":"")+p.id+".png";
const chip=t=>`<span class="type" style="background:${COLORS[t]}">${t}</span>`;
function buildEntries(){entries=[];dex.forEach(base=>{entries.push({...base,baseId:base.id,kind:"Base Pokémon",group:"base"});(forms[base.id]||[]).forEach(f=>entries.push({...f,baseId:base.id,baseName:base.name,gen:base.gen,legend:base.legend,group:f.kind==="Gigantamax"?"gmax":"type"}));(megas[base.id]||[]).forEach(m=>entries.push({...m,baseId:base.id,baseName:base.name,gen:base.gen,legend:base.legend,kind:/primal/i.test(m.name)?"Primal Reversion":"Mega Evolution",group:"mega"}))})}
function renderCatalog(){const q=norm($("search").value),type=$("typeFilter").value,group=$("formFilter").value;const rows=entries.filter(p=>(!q||norm(p.name).includes(q)||norm(p.baseName).includes(q))&&(!type||p.t1===type||p.t2===type)&&(!group||p.group===group)).slice(0,500);$("resultCount").textContent=`Showing ${rows.length}${rows.length===500?" (refine your search)":""} options`;$("catalog").innerHTML=rows.map((p,i)=>{const total=p.s.reduce((a,b)=>a+b,0);return`<button class="variant-card ${p.group}" data-entry="${entries.indexOf(p)}"><img loading="lazy" src="${sprite(p)}" alt="${p.name}" onerror="this.onerror=null;this.src='${ROOT+(shiny?'shiny/':'')+(p.baseId||p.id)+'.png'}'"><b>${p.name}</b><span class="kind">${p.kind}${p.gmax?" · HP ×2":""}</span><small>#${String(p.baseId).padStart(4,"0")} · BST ${total}${p.gmax?` → ${total+p.s[0]} HP-adjusted`:""}</small><div class="types">${[p.t1,p.t2].filter(Boolean).map(chip).join("")}</div></button>`}).join("")||'<p class="full-note">No matching Pokémon or forms.</p>';$("catalog").querySelectorAll("[data-entry]").forEach(b=>b.onclick=()=>add(entries[+b.dataset.entry]))}
function add(p){if(team.length>=6)return;team.push({...p});renderTeam()}
function coverage(){return TYPES.filter(def=>team.some(p=>[p.t1,p.t2,p.attackType].filter(Boolean).some(atk=>(CHART[atk]?.[def]??1)>1))).length}
function renderTeam(){const slots=Array.from({length:6},(_,i)=>team[i]?`<article class="team-slot"><button class="remove" data-remove="${i}" aria-label="Remove">×</button><img src="${sprite(team[i])}" alt="${team[i].name}"><b>${team[i].name}</b><small>${team[i].kind}${team[i].gmax?" · HP ×2":""}</small><div class="types">${[team[i].t1,team[i].t2].filter(Boolean).map(chip).join("")}</div></article>`:`<div class="team-slot empty">Slot ${i+1}</div>`);$("teamGrid").innerHTML=slots.join("");$("teamGrid").querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{team.splice(+b.dataset.remove,1);renderTeam()});const total=team.reduce((n,p)=>n+p.s.reduce((a,b)=>a+b,0),0),effective=total+team.reduce((n,p)=>n+(p.gmax?p.s[0]:0),0);$("teamBst").textContent=total.toLocaleString();$("teamEffective").textContent=effective.toLocaleString();$("teamAvg").textContent=team.length?Math.round(total/team.length):0;$("teamCoverage").textContent=`${coverage()} / 18`}
$("search").oninput=renderCatalog;$("typeFilter").onchange=renderCatalog;$("formFilter").onchange=renderCatalog;$("shinyToggle").onchange=e=>{shiny=e.target.checked;renderCatalog();renderTeam()};$("clearTeam").onclick=()=>{team=[];renderTeam()};
Promise.all([fetch("pokedex.json").then(r=>r.json()),fetch("forms.json").then(r=>r.json()),fetch("megas.json").then(r=>r.json())]).then(data=>{[dex,forms,megas]=data;$("typeFilter").innerHTML+=""+TYPES.map(t=>`<option>${t}</option>`).join("");buildEntries();renderCatalog();renderTeam()}).catch(e=>{$("catalog").innerHTML=`<p class="full-note">Could not load tester data: ${e.message}</p>`});
})();
