(()=>{"use strict";
const $=id=>document.getElementById(id),ROOT="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/",SAVE_KEY="dexle-team-builder:v1";
const REGIONS={1:"Kanto",2:"Johto",3:"Hoenn",4:"Sinnoh",5:"Unova",6:"Kalos",7:"Alola",8:"Galar",9:"Paldea"};
const TYPES=["normal","fire","water","electric","grass","ice","fighting","poison","ground","flying","psychic","bug","rock","ghost","dragon","dark","steel","fairy"];
const COLORS={normal:"#9FA19F",fire:"#E62829",water:"#2980EF",electric:"#C9A000",grass:"#3FA129",ice:"#3D9FB3",fighting:"#D56718",poison:"#9141CB",ground:"#915121",flying:"#6199C9",psychic:"#CF3769",bug:"#71810F",rock:"#8F8961",ghost:"#704170",dragon:"#5060E1",dark:"#50413F",steel:"#508198",fairy:"#CF50CF"};
const CHART={normal:{rock:.5,ghost:0,steel:.5},fire:{fire:.5,water:.5,grass:2,ice:2,bug:2,rock:.5,dragon:.5,steel:2},water:{fire:2,water:.5,grass:.5,ground:2,rock:2,dragon:.5},electric:{water:2,electric:.5,grass:.5,ground:0,flying:2,dragon:.5},grass:{fire:.5,water:2,grass:.5,poison:.5,ground:2,flying:.5,bug:.5,rock:2,dragon:.5,steel:.5},ice:{fire:.5,water:.5,grass:2,ice:.5,ground:2,flying:2,dragon:2,steel:.5},fighting:{normal:2,ice:2,poison:.5,flying:.5,psychic:.5,bug:.5,rock:2,ghost:0,dark:2,steel:2,fairy:.5},poison:{grass:2,poison:.5,ground:.5,rock:.5,ghost:.5,steel:0,fairy:2},ground:{fire:2,electric:2,grass:.5,poison:2,flying:0,bug:.5,rock:2,steel:2},flying:{electric:.5,grass:2,fighting:2,bug:2,rock:.5,steel:.5},psychic:{fighting:2,poison:2,psychic:.5,dark:0,steel:.5},bug:{fire:.5,grass:2,fighting:.5,poison:.5,flying:.5,psychic:2,ghost:.5,dark:2,steel:.5,fairy:.5},rock:{fire:2,ice:2,fighting:.5,ground:.5,flying:2,bug:2,steel:.5},ghost:{normal:0,psychic:2,ghost:2,dark:.5},dragon:{dragon:2,steel:.5,fairy:0},dark:{fighting:.5,psychic:2,ghost:2,dark:.5,fairy:.5},steel:{fire:.5,water:.5,electric:.5,ice:2,rock:2,steel:.5,fairy:2},fairy:{fire:.5,fighting:2,poison:.5,dragon:2,dark:2,steel:.5}};
let dex=[],forms={},megas={},entries=[],team=[],shiny=false,regions=new Set(Object.keys(REGIONS).map(Number));
const norm=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]/g,"");
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const sprite=(p,useShiny=shiny)=>+p.id===10301?"assets/megas/mega-zygarde.png":p[useShiny?"shinySprite":"sprite"]?ROOT+p[useShiny?"shinySprite":"sprite"]:ROOT+(useShiny?"shiny/":"")+p.id+".png";
const chip=t=>`<span class="type" style="background:${COLORS[t]}">${t}</span>`;
const baseTotal=p=>p.s.reduce((a,b)=>a+b,0);
const effectiveStats=p=>p.s.map((v,i)=>p.gmax&&!i?Math.round(v*2.5):v);
const effectiveTotal=p=>effectiveStats(p).reduce((a,b)=>a+b,0);
function buildEntries(){entries=[];dex.forEach(base=>{entries.push({...base,baseId:base.id,kind:"Base Pokémon",group:"base"});(forms[base.id]||[]).forEach(f=>entries.push({...f,baseId:base.id,baseName:base.name,gen:base.gen,region:base.region,legend:base.legend,group:f.gmax?"gmax":"type"}));(megas[base.id]||[]).forEach(m=>entries.push({...m,baseId:base.id,baseName:base.name,gen:base.gen,region:base.region,legend:base.legend,kind:/primal/i.test(m.name)?"Primal Reversion":"Mega Evolution",group:"mega"}))})}
function drawRegions(){$("regionFilters").innerHTML=Object.entries(REGIONS).map(([g,n])=>`<label><input type="checkbox" value="${g}" ${regions.has(+g)?"checked":""}>${n}<small>Gen ${g}</small></label>`).join("");$("regionFilters").querySelectorAll("input").forEach(c=>c.onchange=()=>{c.checked?regions.add(+c.value):regions.delete(+c.value);renderCatalog()})}
function renderCatalog(){const q=norm($("search").value),type=$("typeFilter").value,group=$("formFilter").value;const matched=entries.filter(p=>regions.has(+p.gen)&&(!q||norm(p.name).includes(q)||norm(p.baseName).includes(q))&&(!type||p.t1===type||p.t2===type)&&(!group||p.group===group)),rows=matched.slice(0,400);$("resultCount").textContent=`${matched.length.toLocaleString()} matching Pokémon and forms${matched.length>400?" · showing the first 400":""}`;$("catalog").innerHTML=rows.map(p=>{const index=entries.indexOf(p),total=baseTotal(p),effective=effectiveTotal(p);return`<button class="variant-card ${p.group}" data-entry="${index}"><img loading="lazy" src="${sprite(p)}" alt="${esc(p.name)}" onerror="this.onerror=null;this.src='${ROOT+(shiny?'shiny/':'')+(p.baseId||p.id)+'.png'}'"><b>${esc(p.name)}</b><span class="kind">${esc(p.kind)}${p.gmax?" · HP ×2.5":""}</span><small>${REGIONS[p.gen]} · ${total}${effective!==total?` → ${effective}`:" BST"}</small><div class="types">${[p.t1,p.t2].filter(Boolean).map(chip).join("")}</div></button>`}).join("")||'<p class="full-note">No Pokémon match those filters.</p>';$("catalog").querySelectorAll("[data-entry]").forEach(b=>b.onclick=()=>add(entries[+b.dataset.entry]))}
function add(p){if(team.length>=6){status("Your team already has six members.",true);return}team.push({...p});renderTeam()}
function attackingTypes(){return new Set(team.flatMap(p=>[p.t1,p.t2,p.attackType].filter(Boolean)))}
function coverageTypes(){const moves=attackingTypes();return TYPES.filter(def=>[...moves].some(atk=>(CHART[atk]?.[def]??1)>1))}
function weaknesses(){return TYPES.map(atk=>({type:atk,count:team.filter(p=>[p.t1,p.t2].filter(Boolean).reduce((m,d)=>m*(CHART[atk]?.[d]??1),1)>1).length})).filter(x=>x.count).sort((a,b)=>b.count-a.count||a.type.localeCompare(b.type))}
function renderTeam(){const slots=Array.from({length:6},(_,i)=>team[i]?`<article class="team-slot"><button class="remove" data-remove="${i}" aria-label="Remove ${esc(team[i].name)}">×</button><img src="${sprite(team[i])}" alt="${esc(team[i].name)}"><b>${esc(team[i].name)}</b><small>${esc(team[i].kind)}${team[i].gmax?" · HP ×2.5":""}</small><div class="types">${[team[i].t1,team[i].t2].filter(Boolean).map(chip).join("")}</div><strong>${effectiveTotal(team[i]).toLocaleString()}</strong></article>`:`<button class="team-slot empty" data-empty="1"><span>＋</span>Slot ${i+1}</button>`);$("teamGrid").innerHTML=slots.join("");$("teamGrid").querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{team.splice(+b.dataset.remove,1);renderTeam()});$("teamGrid").querySelectorAll("[data-empty]").forEach(b=>b.onclick=()=>$("search").scrollIntoView({behavior:"smooth",block:"center"}));const total=team.reduce((n,p)=>n+baseTotal(p),0),effective=team.reduce((n,p)=>n+effectiveTotal(p),0),covered=coverageTypes();$("teamBst").textContent=total.toLocaleString();$("teamEffective").textContent=effective.toLocaleString();$("teamAvg").textContent=team.length?Math.round(effective/team.length).toLocaleString():0;$("teamCoverage").textContent=`${covered.length} / 18`;$("memberStats").innerHTML=team.map(p=>`<div><b>${esc(p.name)}</b><span>${effectiveStats(p).map((v,i)=>`${["HP","Atk","Def","SpA","SpD","Spe"][i]} ${v}`).join(" · ")}</span><strong>${effectiveTotal(p)}</strong></div>`).join("");$("coverageTypes").innerHTML=covered.map(chip).join("")||'<span class="analysis-empty">Add Pokémon to analyze coverage.</span>';$("weaknessTypes").innerHTML=weaknesses().map(x=>`<span class="type weakness" style="background:${COLORS[x.type]}">${x.type} <b>${x.count}</b></span>`).join("")||'<span class="analysis-empty">No shared data yet.</span>'}
function saved(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||"[]")}catch(e){return[]}}
function status(text,error=false){$("saveStatus").textContent=text;$("saveStatus").classList.toggle("error",error)}
function saveTeam(){const name=$("teamName").value.trim();if(!name)return status("Give the team a name first.",true);if(!team.length)return status("Add at least one Pokémon first.",true);const rows=saved();rows.unshift({id:Date.now(),name,shiny,team:team.map(p=>({...p})),savedAt:new Date().toISOString()});try{localStorage.setItem(SAVE_KEY,JSON.stringify(rows.slice(0,30)));status("Team saved.");$("activeTeamTitle").textContent=name;renderSaved()}catch(e){status("This browser could not save the team.",true)}}
function renderSaved(){const rows=saved();$("savedTeams").innerHTML=rows.map(row=>`<article class="saved-team"><div><h3>${esc(row.name)}</h3><small>${new Date(row.savedAt).toLocaleDateString()} · ${row.team.length}/6 Pokémon</small></div><div class="saved-sprites">${row.team.map(p=>`<img src="${sprite(p,row.shiny)}" alt="${esc(p.name)}" title="${esc(p.name)}">`).join("")}</div><div class="saved-actions"><button data-load="${row.id}">Load</button><button class="delete" data-delete="${row.id}">Delete</button></div></article>`).join("")||'<p class="full-note">Your named teams will appear here.</p>';$("savedTeams").querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>{const row=saved().find(x=>x.id===+b.dataset.load);if(!row)return;team=row.team.map(p=>({...p}));shiny=!!row.shiny;$("shinyToggle").checked=shiny;$("teamName").value=row.name;$("activeTeamTitle").textContent=row.name;renderCatalog();renderTeam();scrollTo({top:0,behavior:"smooth"})});$("savedTeams").querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{localStorage.setItem(SAVE_KEY,JSON.stringify(saved().filter(x=>x.id!==+b.dataset.delete)));renderSaved()})}
$("search").oninput=renderCatalog;$("typeFilter").onchange=renderCatalog;$("formFilter").onchange=renderCatalog;$("shinyToggle").onchange=e=>{shiny=e.target.checked;renderCatalog();renderTeam()};$("clearTeam").onclick=()=>{team=[];$("teamName").value="";$("activeTeamTitle").textContent="New Team";status("");renderTeam()};$("saveTeam").onclick=saveTeam;$("allRegions").onclick=()=>{regions=new Set(Object.keys(REGIONS).map(Number));drawRegions();renderCatalog()};$("noRegions").onclick=()=>{regions.clear();drawRegions();renderCatalog()};
Promise.all([fetch("pokedex.json").then(r=>r.json()),fetch("forms.json").then(r=>r.json()),fetch("megas.json").then(r=>r.json())]).then(data=>{[dex,forms,megas]=data;$("typeFilter").innerHTML+=TYPES.map(t=>`<option>${t}</option>`).join("");buildEntries();drawRegions();renderCatalog();renderTeam();renderSaved()}).catch(e=>{$("catalog").innerHTML=`<p class="full-note">Could not load team data: ${esc(e.message)}</p>`});
})();
